<a href="https://colab.research.google.com/github/alam292/ecommerce-sales-performance-customer-behavior-analysis/blob/main/Ecommerce_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import  numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

##Data Collection

In [3]:
from google.colab import files

uploaded = files.upload()

Saving orders.csv to orders.csv

In [4]:
df = pd.read_csv("orders.csv")

In [5]:
df

,order_id,customer_id,product_id,seller_id,order_date,order_status,quantity,unit_price,discount,tax_amount,shipping_fee,total_amount,payment_id,payment_method,payment_status,shipping_city,shipping_state,shipping_pincode,delivery_date,customer_rating
0,ORD00000001,CUST030578,PROD0006320,SELL01114,2026-01-03 11:53:24.443541,delivered,3,6119.38,44.14,1162.17,197.02,24035.61,PAY00120243,COD,Completed,Pune,Tamil Nadu,242762.0,2026-09-27 11:22:26.324070,1.0
1,ORD00000002,CUST008134,PROD0006694,SELL00275,2026-01-03 11:54:24.443541,DELIVERED,8,1091.73,17.08,1083.07,489.35,16444.67,PAY00243799,COD,Completed,Noida,Haryana,641740.0,2026-09-27 11:22:26.324096,NaN
2,ORD00000003,CUST018918,PROD0007508,SELL00674,2026-01-03 11:55:24.443541,Delivered,9,2241.77,49.01,402.02,377.91,22191.82,PAY00191877,upi,Completed,Lucknow,Uttar Pradesh,436929.0,2026-10-07 11:22:26.324101,NaN
3,ORD00000004,CUST019490,PROD0001008,SELL00423,2026-01-03 11:56:24.443541,shipped,5,2509.03,5.25,83.49,472.93,3472.73,PAY00032539,Credit Card,Completed,Indore,West Bengal,848774.0,2026-10-02 11:22:26.324104,1.0
4,ORD00000005,CUST009380,PROD0005506,SELL01230,2026-01-03 11:57:24.443541,delivered,6,8852.91,46.81,211.29,193.14,19340.75,PAY00338043,NaN,Completed,Vadodara,Rajasthan,587692.0,2026-09-26 11:22:26.324107,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379495,ORD00379496,CUST031314,PROD0002966,SELL01536,2026-04-02 12:20:24.443541,SHIPPED,1,6586.41,12.60,1460.93,486.94,47030.87,PAY00227888,UPI,Pending,Chennai,Andhra Pradesh,158207.0,2026-10-04 11:22:26.670887,NaN
379496,ORD00379497,CUST017554,PROD0000052,SELL00877,2026-01-26 08:36:24.443541,shipped,10,2053.86,48.25,780.28,424.83,17570.54,PAY00106905,Debit Card,Completed,Surat,West Bengal,439098.0,2026-09-28 11:22:26.410996,NaN
379497,ORD00379498,CUST004270,PROD0005308,SELL00104,2026-02-23 02:42:24.443541,Delivered,7,2215.84,7.89,87.65,226.63,39644.41,PAY00020315,Credit Card,Pending,Kochi,Haryana,143749.0,2026-09-27 11:22:26.518053,3.0
379498,ORD00379499,CUST014634,PROD0004705,SELL00968,NaN,SHIPPED,1,307.62,5.14,1681.09,6.66,27874.52,PAY00375131,Credit Card,Completed,Pune,Gujarat,978790.0,2026-10-04 11:22:26.527057,4.0
379499,ORD00379500,CUST018208,PROD0000765,SELL00764,2026-09-06 14:27:24.443541,Shipped,5,1818.64,9.00,1297.96,386.12,3954.37,PAY00033948,NaN,Completed,Noida,Madhya Pradesh,858450.0,2026-09-02 14:27:24.443541,2.0

##Data Understanding

In [6]:
df.head()

,order_id,customer_id,product_id,seller_id,order_date,order_status,quantity,unit_price,discount,tax_amount,shipping_fee,total_amount,payment_id,payment_method,payment_status,shipping_city,shipping_state,shipping_pincode,delivery_date,customer_rating
0,ORD00000001,CUST030578,PROD0006320,SELL01114,2026-01-03 11:53:24.443541,delivered,3,6119.38,44.14,1162.17,197.02,24035.61,PAY00120243,COD,Completed,Pune,Tamil Nadu,242762.0,2026-09-27 11:22:26.324070,1.0
1,ORD00000002,CUST008134,PROD0006694,SELL00275,2026-01-03 11:54:24.443541,DELIVERED,8,1091.73,17.08,1083.07,489.35,16444.67,PAY00243799,COD,Completed,Noida,Haryana,641740.0,2026-09-27 11:22:26.324096,NaN
2,ORD00000003,CUST018918,PROD0007508,SELL00674,2026-01-03 11:55:24.443541,Delivered,9,2241.77,49.01,402.02,377.91,22191.82,PAY00191877,upi,Completed,Lucknow,Uttar Pradesh,436929.0,2026-10-07 11:22:26.324101,NaN
3,ORD00000004,CUST019490,PROD0001008,SELL00423,2026-01-03 11:56:24.443541,shipped,5,2509.03,5.25,83.49,472.93,3472.73,PAY00032539,Credit Card,Completed,Indore,West Bengal,848774.0,2026-10-02 11:22:26.324104,1.0
4,ORD00000005,CUST009380,PROD0005506,SELL01230,2026-01-03 11:57:24.443541,delivered,6,8852.91,46.81,211.29,193.14,19340.75,PAY00338043,NaN,Completed,Vadodara,Rajasthan,587692.0,2026-09-26 11:22:26.324107,4.0

In [7]:
df.tail()

,order_id,customer_id,product_id,seller_id,order_date,order_status,quantity,unit_price,discount,tax_amount,shipping_fee,total_amount,payment_id,payment_method,payment_status,shipping_city,shipping_state,shipping_pincode,delivery_date,customer_rating
379495,ORD00379496,CUST031314,PROD0002966,SELL01536,2026-04-02 12:20:24.443541,SHIPPED,1,6586.41,12.60,1460.93,486.94,47030.87,PAY00227888,UPI,Pending,Chennai,Andhra Pradesh,158207.0,2026-10-04 11:22:26.670887,NaN
379496,ORD00379497,CUST017554,PROD0000052,SELL00877,2026-01-26 08:36:24.443541,shipped,10,2053.86,48.25,780.28,424.83,17570.54,PAY00106905,Debit Card,Completed,Surat,West Bengal,439098.0,2026-09-28 11:22:26.410996,NaN
379497,ORD00379498,CUST004270,PROD0005308,SELL00104,2026-02-23 02:42:24.443541,Delivered,7,2215.84,7.89,87.65,226.63,39644.41,PAY00020315,Credit Card,Pending,Kochi,Haryana,143749.0,2026-09-27 11:22:26.518053,3.0
379498,ORD00379499,CUST014634,PROD0004705,SELL00968,NaN,SHIPPED,1,307.62,5.14,1681.09,6.66,27874.52,PAY00375131,Credit Card,Completed,Pune,Gujarat,978790.0,2026-10-04 11:22:26.527057,4.0
379499,ORD00379500,CUST018208,PROD0000765,SELL00764,2026-09-06 14:27:24.443541,Shipped,5,1818.64,9.00,1297.96,386.12,3954.37,PAY00033948,NaN,Completed,Noida,Madhya Pradesh,858450.0,2026-09-02 14:27:24.443541,2.0

In [8]:
df.shape

(379500, 20)

In [9]:
df.columns

Index(['order_id', 'customer_id', 'product_id', 'seller_id', 'order_date',
       'order_status', 'quantity', 'unit_price', 'discount', 'tax_amount',
       'shipping_fee', 'total_amount', 'payment_id', 'payment_method',
       'payment_status', 'shipping_city', 'shipping_state', 'shipping_pincode',
       'delivery_date', 'customer_rating'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379500 entries, 0 to 379499
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order_id          379500 non-null  object
 1   customer_id       379500 non-null  object
 2   product_id        379500 non-null  object
 3   seller_id         379500 non-null  object
 4   order_date        368117 non-null  object
 5   order_status      379500 non-null  object
 6   quantity          379500 non-null  int64
 7   unit_price        379500 non-null  float64
 8   discount          379500 non-null  float64
 9   tax_amount        379500 non-null  float64
 10  shipping_fee      379500 non-null  float64
 11  total_amount      379500 non-null  float64
 12  payment_id        379500 non-null  object
 13  payment_method    331919 non-null  object
 14  payment_status    379500 non-null  object
 15  shipping_city     379500 non-null  object
 16  shipping_state    379500 non-null  object
 17  shipping_pincode  368244 non-null  float64
 18  delivery_date     379281 non-null  object
 19  customer_rating   317666 non-null  float64
dtypes: float64(7), int64(1), object(12)
memory usage: 57.9+ MB

In [11]:
df.describe()

,quantity,unit_price,discount,tax_amount,shipping_fee,total_amount,shipping_pincode,customer_rating
count,379500.000000,379500.000000,379500.000000,379500.000000,379500.000000,379500.000000,368244.000000,317666.000000
mean,72.647049,14929.479919,26.498286,1001.656230,249.739616,25079.195357,549918.581370,3.065525
std,817.079087,98952.862262,23.371946,577.319061,144.500792,14412.345027,260052.677007,1.563897
min,-5.000000,-100.000000,-50.000000,0.010000,0.000000,100.140000,100003.000000,0.000000
25%,3.000000,2524.580000,12.420000,501.327500,124.820000,12593.152500,324760.500000,2.000000
50%,5.000000,5053.405000,25.150000,1004.925000,249.300000,25077.975000,549805.500000,3.000000
75%,8.000000,7570.042500,37.920000,1501.660000,374.630000,37560.725000,775293.250000,4.000000
max,9999.000000,999999.000000,200.000000,1999.980000,500.000000,49999.990000,999998.000000,10.000000

In [12]:
df.describe(include = "object")

,order_id,customer_id,product_id,seller_id,order_date,order_status,payment_id,payment_method,payment_status,shipping_city,shipping_state,delivery_date
count,379500,379500,379500,379500,368117,379500,379500,331919,379500,379500,379500,379281
unique,372106,38375,7650,1537,365933,10,264730,7,4,20,16,377031
top,ORD00192207,CUST006550,PROD0005664,SELL00071,2026-05-07 01:06:24.443541,Cancelled,PAY00010828,Wallet,Failed,Surat,West Bengal,2026-09-24 11:22:27.091781
freq,4,35,122,532,2,38225,8,47571,95159,19154,24038,2

In [13]:
df.isnull().sum()

order_id                0
customer_id             0
product_id              0
seller_id               0
order_date          11383
order_status            0
quantity                0
unit_price              0
discount                0
tax_amount              0
shipping_fee            0
total_amount            0
payment_id              0
payment_method      47581
payment_status          0
shipping_city           0
shipping_state          0
shipping_pincode    11256
delivery_date         219
customer_rating     61834
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.nunique()

order_id            372106
customer_id          38375
product_id            7650
seller_id             1537
order_date          365933
order_status            10
quantity                13
unit_price          308361
discount              5004
tax_amount          169687
shipping_fee         49972
total_amount        363159
payment_id          264730
payment_method           7
payment_status           4
shipping_city           20
shipping_state          16
shipping_pincode    300823
delivery_date       377031
customer_rating          9
dtype: int64

In [16]:
df["shipping_city"].unique()

array(['Pune', 'Noida', 'Lucknow', 'Indore', 'Vadodara', 'Bengaluru',
       'Bhopal', 'Nagpur', 'Kochi', 'Mumbai', 'Jaipur', 'Hyderabad',
       'Visakhapatnam', 'Chennai', 'Kolkata', 'Ahmedabad', 'Delhi',
       'Patna', 'Chandigarh', 'Surat'], dtype=object)

In [17]:
df.dtypes

order_id             object
customer_id          object
product_id           object
seller_id            object
order_date           object
order_status         object
quantity              int64
unit_price          float64
discount            float64
tax_amount          float64
shipping_fee        float64
total_amount        float64
payment_id           object
payment_method       object
payment_status       object
shipping_city        object
shipping_state       object
shipping_pincode    float64
delivery_date        object
customer_rating     float64
dtype: object

##Data Cleaning

missing value

In [25]:
df.isnull().sum()

order_id                0
customer_id             0
product_id              0
seller_id               0
order_date          11383
order_status            0
quantity                0
unit_price              0
discount                0
tax_amount              0
shipping_fee            0
total_amount            0
payment_id              0
payment_method      47581
payment_status          0
shipping_city           0
shipping_state          0
shipping_pincode    11256
delivery_date         219
customer_rating     61834
dtype: int64