In [6]:
import  numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

##Data Collection

In [7]:
from pathlib import Path

# Works when the notebook runs from either the project root or notebooks/.
data_dir = Path("messy datasets")
if not data_dir.is_dir():
    data_dir = Path("..") / "messy datasets"

customers = pd.read_csv(data_dir / "customers.csv")
orders = pd.read_csv(data_dir / "orders.csv")
payments = pd.read_csv(data_dir / "payments.csv")
products = pd.read_csv(data_dir / "products.csv")
sellers = pd.read_csv(data_dir / "sellers.csv")

print({
    "customers": customers.shape,
    "orders": orders.shape,
    "payments": payments.shape,
    "products": products.shape,
    "sellers": sellers.shape,
})

{'customers': (38610, 10), 'orders': (379500, 20), 'payments': (228000, 7), 'products': (7800, 9), 'sellers': (1575, 7)}

In [ ]:
customer

,customer_id,customer_name,gender,age,email,phone,city,state,signup_date,customer_segment
0,CUST000001,Aryan Maharaj,Unknown,73,ronithlanka@example.org,4.976462e+09,Indore,Tamil Nadu,2022-05-23 04:22:23.893543,VIP
1,CUST000002,Udant Dewan,FEMALE,66,tanveerpillay@example.com,NaN,Mumbai,Maharashtra,2022-05-23 05:22:23.893543,New
2,CUST000003,Gagan Sami,F,59,semraagini@example.net,8.629780e+08,Bengaluru,Karnataka,2022-05-23 06:22:23.893543,Regular
3,CUST000004,Ayushman Chander,Unknown,19,qkaur@example.com,1.971838e+08,Visakhapatnam,Tamil Nadu,2022-05-23 07:22:23.893543,New
4,CUST000005,Viraj Tiwari,M,52,khalsadivya@example.net,9.184122e+08,Kochi,Haryana,2022-05-23 08:22:23.893543,Inactive
...,...,...,...,...,...,...,...,...,...,...
38605,CUST013313,Omya Kumar,male,55,dharchavvi@example.com,6.505487e+09,Bhopal,Bihar,2023-11-28 20:22:23.893543,New
38606,CUST025181,Ishwar Badami,NaN,47,braravni@example.org,3.809622e+09,Chennai,Andhra Pradesh,2025-04-06 08:22:23.893543,Premium
38607,CUST020659,Amruta Tandon,F,63,parmerwaida@example.com,9.986743e+09,Chandigarh,West Bengal,2024-09-29 22:22:23.893543,Premium
38608,CUST033682,Tanay Dalal,F,46,walianitara@example.com,7.558714e+09,Vadodara,Delhi,2026-03-26 13:22:23.893543,Inactive
38609,CUST025991,Onveer Joshi,male,52,ekapad57@example.com,5.644085e+08,Ahmedabad,Kerala,2025-05-10 02:22:23.893543,Inactive

Data Understanding

In [9]:
cust = customers
cust

,customer_id,customer_name,gender,age,email,phone,city,state,signup_date,customer_segment
0,CUST000001,Aryan Maharaj,Unknown,73,ronithlanka@example.org,4.976462e+09,Indore,Tamil Nadu,2022-05-23 04:22:23.893543,VIP
1,CUST000002,Udant Dewan,FEMALE,66,tanveerpillay@example.com,NaN,Mumbai,Maharashtra,2022-05-23 05:22:23.893543,New
2,CUST000003,Gagan Sami,F,59,semraagini@example.net,8.629780e+08,Bengaluru,Karnataka,2022-05-23 06:22:23.893543,Regular
3,CUST000004,Ayushman Chander,Unknown,19,qkaur@example.com,1.971838e+08,Visakhapatnam,Tamil Nadu,2022-05-23 07:22:23.893543,New
4,CUST000005,Viraj Tiwari,M,52,khalsadivya@example.net,9.184122e+08,Kochi,Haryana,2022-05-23 08:22:23.893543,Inactive
...,...,...,...,...,...,...,...,...,...,...
38605,CUST013313,Omya Kumar,male,55,dharchavvi@example.com,6.505487e+09,Bhopal,Bihar,2023-11-28 20:22:23.893543,New
38606,CUST025181,Ishwar Badami,NaN,47,braravni@example.org,3.809622e+09,Chennai,Andhra Pradesh,2025-04-06 08:22:23.893543,Premium
38607,CUST020659,Amruta Tandon,F,63,parmerwaida@example.com,9.986743e+09,Chandigarh,West Bengal,2024-09-29 22:22:23.893543,Premium
38608,CUST033682,Tanay Dalal,F,46,walianitara@example.com,7.558714e+09,Vadodara,Delhi,2026-03-26 13:22:23.893543,Inactive
38609,CUST025991,Onveer Joshi,male,52,ekapad57@example.com,5.644085e+08,Ahmedabad,Kerala,2025-05-10 02:22:23.893543,Inactive